/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

import java.awt.Cursor;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author alomari
 */
public class Splash extends javax.swing.JFrame {

    private String role="";
    
    public Splash() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("PHILADELPHIA MANAGEMENT SYSTEM");
        try {
            File f = new File("bbb.png");
            Image img = ImageIO.read(f);
            Image newImg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_AREA_AVERAGING);
            jLabel1.setIcon(new ImageIcon(newImg));
        } catch (IOException ex) {

        }
        
//        try {
//            File f = new File("Picture6.png");
//            Image img = ImageIO.read(f);
//            Image newImg = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_AREA_AVERAGING);
//            jLabel2.setIcon(new ImageIcon(newImg));
//        } catch (IOException ex) {
//            
//        }
        
        try {
            File f = new File("minus.png");
            Image img = ImageIO.read(f);
            Image newImg = img.getScaledInstance(lblMinus.getWidth(), lblMinus.getHeight(), Image.SCALE_AREA_AVERAGING);
            lblMinus.setIcon(new ImageIcon(newImg));
        } catch (IOException ex) {

        }
        
        try {
            File f = new File("close.png");
            Image img = ImageIO.read(f);
            ImageIcon icon = new ImageIcon(img);
            Image newImg = img.getScaledInstance(lblClose.getWidth(), lblClose.getHeight(), Image.SCALE_AREA_AVERAGING);
            lblClose.setIcon(new ImageIcon(newImg));
        } catch (IOException ex) {

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        lblMinus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_adminSys = new javax.swing.JLabel();
        btn_studentSys = new javax.swing.JLabel();
        btn_academicSys = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setText("jLabel3");
        lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCloseMouseMoved(evt);
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 50, 50));

        lblMinus.setForeground(new java.awt.Color(255, 255, 255));
        lblMinus.setText("PHILADELPHIA MANAGEMENT SYSTEM");
        lblMinus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinusMouseMoved(evt);
            }
        });
        lblMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinusMouseClicked(evt);
            }
        });
        getContentPane().add(lblMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 40, 30));

        jLabel2.setBackground(new java.awt.Color(94, 116, 237));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 108));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PHILADELPHIA MANAGEMENT SYSTEM");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 70));

        btn_adminSys.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_adminSysMouseMoved(evt);
            }
        });
        btn_adminSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminSysMouseClicked(evt);
            }
        });
        getContentPane().add(btn_adminSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 310, 230));

        btn_studentSys.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_studentSysMouseMoved(evt);
            }
        });
        btn_studentSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_studentSysMouseClicked(evt);
            }
        });
        getContentPane().add(btn_studentSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 300, 230));

        btn_academicSys.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_academicSysMouseMoved(evt);
            }
        });
        btn_academicSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_academicSysMouseClicked(evt);
            }
        });
        getContentPane().add(btn_academicSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 300, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bbb.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
        lblClose.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCloseMouseMoved

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseMoved
        lblMinus.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblMinusMouseMoved

    private void lblMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseClicked
        this.setState(WIDTH);
    }//GEN-LAST:event_lblMinusMouseClicked

    private void btn_studentSysMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studentSysMouseMoved
        btn_studentSys.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_studentSysMouseMoved

    private void btn_academicSysMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_academicSysMouseMoved
        btn_academicSys.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_academicSysMouseMoved

    private void btn_adminSysMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminSysMouseMoved
        btn_adminSys.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_adminSysMouseMoved

    private void btn_studentSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studentSysMouseClicked
        role="student";
        this.setVisible(false);
        new Login(role).setVisible(true);
    }//GEN-LAST:event_btn_studentSysMouseClicked

    private void btn_academicSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_academicSysMouseClicked
        role="lecturer";
        this.setVisible(false);
        new Login(role).setVisible(true);
    }//GEN-LAST:event_btn_academicSysMouseClicked

    private void btn_adminSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminSysMouseClicked
        role="admin";
        this.setVisible(false);
        new Login(role).setVisible(true);
    }//GEN-LAST:event_btn_adminSysMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_academicSys;
    private javax.swing.JLabel btn_adminSys;
    private javax.swing.JLabel btn_studentSys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinus;
    // End of variables declaration//GEN-END:variables
}
